apiVersion: v1
kind: Service
metadata:
    name: image1
Container:
    name : jdk
    image: ubuntu-latest
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: HelloWorld
